<?php
$resourceMedia = $resource->media();
$this->headLink()->prependStylesheet('//cdn.jsdelivr.net/npm/@accessible360/accessible-slick@1.0.1/slick/slick.min.css');
$this->headLink()->prependStylesheet('//cdn.jsdelivr.net/npm/@accessible360/accessible-slick@1.0.1/slick/slick-theme.min.css');
$this->headScript()->appendFile('//cdn.jsdelivr.net/npm/@accessible360/accessible-slick@1.0.1/slick/slick.min.js');
$this->headLink()->appendStylesheet($this->assetUrl('css/slickandslide.css'));
$this->headScript()->appendFile($this->assetUrl('js/slickandslide.js'));

$imgForCarousel = [];
$pdfsForDisplay = [];
$allOthers = [];
if(isset($resourceMedia) && count($resourceMedia) > 0) {
    foreach($resourceMedia as $media) {
        if(null !== $media->extension()) {
            if(preg_match('/(?:jpg|jpeg|png)/', $media->extension(), $matches) === 1) {
                $imgForCarousel[] = $media;
            }
            if(preg_match('/(?:pdf)/', $media->extension(), $matches) === 1) {
                $pdfsForDisplay[] = $media;
            }
            if(preg_match('/(?!jpg|jpeg|png|pdf)/', $media->extension(), $matches) === 1) {
                $allOthers[] = $media;
            }
        }
    }
}
?>
<?php if ($resourceMedia): ?>
<div class="media-embeds">
    <div class="slicked-items">
        <?php foreach ($imgForCarousel as $media): ?>
            <?php echo $media->render(); ?>
        <?php endforeach; ?>
    </div>
    <div class="pdf-items">
        <?php foreach ($pdfsForDisplay as $media): ?>
            <object className="pdf" 
                data="<?php echo $media->originalUrl(); ?>"
                width="90%"
                height="900">
            </object>
        <?php endforeach; ?>
    </div>
    <!-- will add allOthers if needed -->
</div>
<?php endif; ?>
